---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: Home Lab
    background: "#1a1b26"
    cardBlur: 10
  services.yaml: |
    - Infrastructure:
        - OpenMediaVault:
            icon: openmediavault
            href: http://192.168.8.15
            description: NAS Management
        - MinIO:
            icon: minio
            href: https://openmediavault.home:9001
            description: Object Storage
    - Cluster:
        - K3s:
            icon: kubernetes
            href: http://192.168.8.248:6443
            description: Control Plane
        - Grafana:
            icon: grafana
            href: http://grafana.home
            description: Cluster Monitoring
  widgets.yaml: |
    - search:
        provider: google
        focus: true
    - datetime:
        format:
          dateStyle: long
          timeStyle: short
  bookmarks.yaml: |
    - Github:
        - abbr: GH
          href: https://github.com/
  docker.yaml: ""
  kubernetes.yaml: ""
