---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-downloads-pv
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.8.15
    path: /share/qbittorent
  mountOptions:
    - nfsvers=4.2
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client-static
