all:
  vars:
    ansible_user: darthv
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3

  children:

    arch:
      hosts:
        arch01:
        arch02:
        arch03:


    vms:
      hosts:
        vm01:
        vm02:
        vm03:

    k3s_master:
      hosts:
        vm01:
          ansible_host: 192.168.8.248

    k3s_worker:
      hosts:
        vm02:
          ansible_host: 192.168.8.249
        vm03:
          ansible_host: 192.168.8.101

    omv:
      hosts:
        openmediavault:

    network:
      hosts:
        router:
          ansible_host: 192.168.8.253
          ansible_user: root
