all:
  vars:
    ansible_user: darthv
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3

  children:

    # -------------------------
    # HOSTS FISICOS KVM
    # -------------------------
    arch:
      hosts:
        arch01:
          ansible_host: 192.168.8.11
          hostname_fqdn: arch01.home

        arch02:
          ansible_host: 192.168.8.12
          hostname_fqdn: arch02.home

        arch03:
          ansible_host: 192.168.8.13
          hostname_fqdn: arch03.home

    # -------------------------
    # NAS / STORAGE
    # -------------------------
    omv:
      hosts:
        openmediavault:
          ansible_host: 192.168.8.15
          hostname_fqdn: openmediavault.home

    # -------------------------
    # MANAGEMENT VM
    # -------------------------
    mgmt:
      hosts:
        mgmt:
          ansible_host: 192.168.8.102
          hostname_fqdn: mgmt.home

    # -------------------------
    # VIRTUAL MACHINES
    # -------------------------
    vms:
      hosts:
        vm01:
          ansible_host: 192.168.8.248
          hostname_fqdn: vm01.home

        vm02:
          ansible_host: 192.168.8.249
          hostname_fqdn: vm02.home

        vm03:
          ansible_host: 192.168.8.101
          hostname_fqdn: vm03.home

