---
- name: Cleanup libvirt VMs and reset network
  hosts: arch
  become: true

  tasks:

    - name: Destroy VMs if running
      command: "virsh destroy {{ vm.name }}"
      loop: "{{ vm_list }}"
      loop_control:
        loop_var: vm
      when: vm.target_host == inventory_hostname
      ignore_errors: true

    - name: Undefine VMs
      command: "virsh undefine {{ vm.name }}"
      loop: "{{ vm_list }}"
      loop_control:
        loop_var: vm
      when: vm.target_host == inventory_hostname
      ignore_errors: true

    - name: Remove VM disks
      file:
        path: "/var/lib/libvirt/images/{{ vm.name }}.qcow2"
        state: absent
      loop: "{{ vm_list }}"
      loop_control:
        loop_var: vm
      when: vm.target_host == inventory_hostname

    - name: Destroy default network
      command: virsh net-destroy default
      ignore_errors: true

    - name: Start default network
      command: virsh net-start default
