---
- name: Create Management VM
  hosts: arch01
  become: true

  vars:
    vm_list:
      - name: mgmt
        mac: "52:54:00:aa:bb:04"

    base_image_url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
    base_image_path: "/var/lib/libvirt/base/ubuntu.img"
    vm_disk_size: "20G"

    ssh_public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  roles:
    - cloud-vms
