apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: harbor

resources:
  - namespace.yaml

helmCharts:
  - name: harbor
    repo: https://helm.goharbor.io
    version: 1.14.0
    releaseName: harbor
    namespace: harbor
    valuesInline:
      expose:
        type: ingress
        tls:
          enabled: true
          certSource: secret
          secret:
            secretName: "harbor-tls"
        ingress:
          hosts:
            core: registry.home
          className: traefik
          annotations:
            cert-manager.io/cluster-issuer: homelab-ca
            ingress.kubernetes.io/proxy-body-size: "0"
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
      externalURL: https://registry.home
      persistence:
        persistentVolumeClaim:
          registry:
            storageClass: "nfs-client"
            size: 10Gi
          jobservice:
            storageClass: "nfs-client"
          database:
            storageClass: "nfs-client"
          redis:
            storageClass: "nfs-client"
          trivy:
            storageClass: "nfs-client"
